# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ATI (Avances en Tecnologías Informáticas)
email: clouddi@ual.es
description: > # Bla bla bla.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cloud.di.ual.es" # the base hostname & protocol for your site
# twitter_username: ualclouddi
github_username:  ualclouddi

# Build settings
markdown: kramdown
